name: cmis
version: 6.2.0
description: A CMIS 1.1 compliant browser and server based client for Dart.
homepage: https://github.com/shamblett/cmis
environment:
  sdk: '>=3.7.0 <4.0.0'

funding:
  - https://www.darticulate.com/#funding

dependencies:
  json_object_lite: '^4.0.2'
  http: '^1.6.0'
  mime: '^2.0.0'
  web: '^1.1.1'

dev_dependencies:
  test: '^1.28.0'
  build_runner: '^2.10.4'
  build_test: '^3.5.4'
  build_web_compilers: '^4.1.5'
  lints: '^6.0.0'
